#!/usr/bin/env bash

# Function to fetch and display information about a specific subdomain
fetch_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    local output_awk='{print "The subdomain", $1, "is a", $7, "record and points to", $8}'
    
    dig "$subdomain.$domain" | awk -F'\t' '/ANSWER SECTION:/ {print $1, $2}' | awk "$output_awk"
}

# Function to display information for the default subdomains
display_default_subdomains_info() {
    local domain="$1"
    
    local subdomains=("www" "lb-01" "web-01" "web-02")
    
    for subdomain in "${subdomains[@]}"; do
        fetch_subdomain_info "$domain" "$subdomain"
    done
}

# Check if both domain and subdomain arguments are provided
if [ $# -eq 2 ]; then
    fetch_subdomain_info "$1" "$2"
# Check if only the domain argument is provided
elif [ $# -eq 1 ]; then
    display_default_subdomains_info "$1"
else
    echo "Usage: $0 domain [subdomain]"
fi
