#!/usr/bin/env bash
# This code moves a file from a client to a server.

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
