#!/usr/bin/env bash
# This script sets up the nginx server in a way that when accessing
# /redirect_me, it will lead to a different webpage through redirection.

sudo apt update
sudo apt install nginx -y
sudo ufw allow 80
sudo ufw allow 22
sudo ufw enable

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
