#!/usr/bin/env bash
# This script configures Nginx to include a custom message in its HTTP response.

sudo apt update
sudo apt install nginx -y
sudo sed -i "6i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
