#!/usr/bin/env bash
# This script installs and sets up HAproxy.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 241443-web-01 54.87.157.153
	server 241443-web-02 52.91.124.211" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
