#!/usr/bin/env bash
# This script installs and sets up HAproxy.

sudo apt update
sudo apt install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 241443-web-01 54.87.157.153:80 check\n\tserver 241443-web-02 52.91.124.211:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
