#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal
# Function to handle SIGTERM and SIGQUIT signals

cleanup() {
  echo "Deleting PID file and terminating the script."
  rm -f /var/run/myscript.pid
  exit 0
}

# Function to handle SIGINT signal
interrupt() {
  echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
terminate() {
  echo "I hate the kill command"
}

# Register signal handlers
trap cleanup SIGQUIT SIGTERM
trap interrupt SIGINT
trap terminate SIGTERM

# Create PID file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done
