#!/usr/bin/env bash
#This script extends previous exercise command and displays line containing the bash word
#Bash script that displays a list of currently running processes.

$"ps" "faux" | grep "bash"
