#!/usr/bin/env bash
# Displays 1-100 with exceptions in multiples of 3,5 or both
# fizzbuzz challenge

for i in {1..100}
do
if ((i % 15 == 0))
    then
    echo "FizzBuzz"

elif ((i % 5 == 0))
    then
    echo "Buzz"

elif (( i % 3 == 0))
    then
    echo "Fizz"

else
    echo "$i"
fi

done
