#!/usr/bin/env bash
# analyzes content of /etc/passwd file
# display username, user id and home directory for eac line of /etc/paswwd

while read -r passwd;
do
    echo "$passwd" | cut -d ":" -f1,2,6

done < "/etc/passwd"
