#!/usr/bin/env bash
# Displays the IP address and HTTP codes
# the dispaly is from the Apache log access file
# display the number of occurrences


awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
