#!/usr/bin/env bash
# This script displays Best School 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line
# displays hi on the 9thh line
i=1

while (( i <= 10 )); do
	echo "$string"

	if [[ $i = 9 ]]; then
		echo "Hi"
	fi
	((i++))

done
